# Generated by Django 5.0 on 2023-12-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ownner',
            field=models.CharField(default=101010, max_length=255),
            preserve_default=False,
        ),
    ]
