# Generated by Django 5.0 on 2023-12-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_ownner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='ownner',
            new_name='owner',
        ),
    ]
