# Generated by Django 5.0 on 2023-12-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ownner_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AlterField(
            model_name='job',
            name='ed_level',
            field=models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Tecnólogo'), ('3', 'Ensino Superior'), ('4', 'Pós / MBA / Mestrado'), ('5', 'Doutorado')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Tecnólogo'), ('3', 'Ensino Superior'), ('4', 'Pós / MBA / Mestrado'), ('5', 'Doutorado')], default='1', max_length=1),
        ),
    ]
