# Generated by Django 5.0 on 2023-12-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_job_description_alter_job_ed_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('1', 'Até 1.000'), ('2', 'De 1.000 a 2.000'), ('3', 'De 2.000 a 3.000'), ('4', 'Acima de 3.000')], default='1', max_length=1),
        ),
    ]
