# Generated by Django 5.0 on 2023-12-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobapplication_aplplication_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='aplplication_date',
            new_name='application_date',
        ),
    ]
