# Generated by Django 5.0 on 2023-12-11 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_jobapplication_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
