# Generated by Django 5.0 on 2023-12-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jobapplication_applicant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_opening_id',
            new_name='job_opening',
        ),
    ]
