# Generated by Django 5.0 on 2023-12-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_applicant_salary_expec_jobapplication_applicant_salary_espec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_salary_espec',
            new_name='applicant_salary_expec',
        ),
    ]
