# Generated by Django 5.0 on 2023-12-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_applicant_salary_espec_jobapplication_applicant_salary_expec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_salary_expec',
            new_name='applicant_salary_epec',
        ),
        migrations.AddField(
            model_name='job',
            name='applicants_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
