# Generated by Django 5.0 on 2023-12-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_applicant_salary_expec_jobapplication_applicant_salary_epec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant_salary_epec',
            new_name='applicant_salary_expec',
        ),
    ]
